server:
  port: 9090
spring:
  #data:
    #mongodb:
      #database: test
      #uri: mongodb://localhost:27017
      
      
    redis:
      port: 6379
      host: localhost


logging.level.org.springframework.web: DEBUG
spring.datasource.driver: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/c2gx
spring.datasource.username: root
spring.datasource.password: J3$$3root

spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: gctestingemail@gmail.com
spring.mail.password: gc@123456
spring.mail.protocol: smtp
spring.mail.tls: true
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.ssl.trust: smtp.gmail.com  
spring.http.encoding.charset: UTF-8
spring.http.encoding.enabled: true
spring.http.encoding.force: true      

spring.jpa.properties.hibernate.jdbc.time_zone : UTC

spring.servlet.multipart.enabled : true
spring.servlet.multipart.file-size-threshold : 2KB
spring.servlet.multipart.max-file-size : 200MB
spring.servlet.multipart.max-request-size : 215MB

